### ISSUE TITLE
ambiguity in setup_hipporag_colbert.sh

### ISSUE THREAD

**Issue by Reza-Ardestani** [OSU-NLP-Group/HippoRAG#37]
Hello, 

In Setup_hiporag_colbert.sh you are firstly creating the openie and doing NER for query.json files and I got that. 
1) What I didn't quite get that is why are you calling create_graph.py twice?
2) What does "kb_to_kb" stand for and what is its use-case?
3) similar to my previous question, what is "query_to_kb"?
4) What is "_fact_and_sim_graph_phrase_dict_ents_only_lower_preprocess_ner.v3.subset.pkl" exactly ? and why "subset" ?
5) For online retrieval we need matrix P ( noun_phrases, Passages), where is this matrix stored?
6) Similarly, we need OpenIE KG, with noun_phrases as nodes and | E| + | Ep | as edges. Where is this stored?

Thank you,

--------

`data=$1
extraction_model=$2  # LLM using LangChain, e.g., 'gpt-3.5-turbo' or 'meta-llama/Llama-3-8b-chat-hf'
available_gpus=$3
syn_thresh=$4
llm_api=$5 # e.g., 'openai', 'together'
extraction_type=ner

#Running Open Information Extraction
python src/openie_with_retrieval_option_parallel.py --dataset $data --llm $llm_api --model_name $extraction_model --run_ner --num_passages all  # NER and OpenIE for passages
python src/named_entity_extraction_parallel.py --dataset $data --llm $llm_api --model_name $extraction_model  # NER for queries

#Creating ColBERT Graph
python src/create_graph.py --dataset $data --model_name colbertv2 --extraction_model $extraction_model --threshold $syn_thresh --extraction_type $extraction_type --cosine_sim_edges

#Getting Nearest Neighbor Files
CUDA_VISIBLE_DEVICES=$available_gpus python src/colbertv2_knn.py --filename output/kb_to_kb.tsv
CUDA_VISIBLE_DEVICES=$available_gpus python src/colbertv2_knn.py --filename output/query_to_kb.tsv
create_graph
python src/create_graph.py --dataset $data --model_name colbertv2 --extraction_model $extraction_model --threshold $syn_thresh -- --extraction_type $extraction_type --cosine_sim_edges

#ColBERTv2 Indexing for Entity Retrieval & Ensembling
CUDA_VISIBLE_DEVICES=$available_gpus python3 src/colbertv2_indexing.py \
 --dataset $data \
 --phrase output/$data'_facts_and_sim_graph_phrase_dict_ents_only_lower_preprocess_ner.v3.subset.p' \
 --corpus 'data/'$data'_corpus.json'`

**Comment by bernaljg** [comment]
Hi,

Thank you for your detailed questions about our repo, I'll answer them below:

1. What I didn't quite get that is why are you calling create_graph.py twice?

The first create_graph.py call sets up the graph and saves the auxiliary files 'kb_to_kb' and 'query_to_kb' which are later used to run the kNN algorithm. The second call to create_graph.py adds synonymy edges to the graph and saves the final graph for later use by HippoRAG.

2. What does "kb_to_kb" stand for and what is its use-case?
3. similar to my previous question, what is "query_to_kb"?

We use the kb_to_kb file to find synonyms to connect within the KB by getting each node's nearest neighbors. The query_to_kb file helps us obtain the nearest KB neighbors for each entity found in the queries but this process is not essential, just makes the online process slightly faster.

4. What is "_fact_and_sim_graph_phrase_dict_ents_only_lower_preprocess_ner.v3.subset.pkl" exactly ? and why "subset" ?

`fact_and_sim_graph` denotes that the graph is made with fact triples and similarity edges.
`phrase_dict` is the object stored in this pickle file.
`ents_only_lower_preprocess_ner` denotes preprocessing and extraction design choices.
`subset` is due to the fact that we used only subsets of the benchmark datasets since the full datasets were too large.
 
5. For online retrieval we need matrix P ( noun_phrases, Passages), where is this matrix stored?

The information is stored in two pickle files, one which contains the substring `_graph_doc_to_facts_csr_` and stores a (Passages x Facts) sparse matrix and a second one containing the substring `_graph_facts_to_phrases_csr` which stores a (Facts x Nodes) sparse matrix.

6. Similarly, we need OpenIE KG, with noun_phrases as nodes and | E| + | Ep | as edges. Where is this stored?

You can find the OpenIE KG under the `output` directory i.e. [output/openie_musique_results_ner_gpt-3.5-turbo-1106_11656.json](https://github.com/OSU-NLP-Group/HippoRAG/blob/main/output/openie_musique_results_ner_gpt-3.5-turbo-1106_11656.json).

Hopefully these answers will make things a bit clearer!

**Comment by Reza-Ardestani** [comment]
Thank you for your response.
